
$("#app").click(function () {
    $("#app").css("backgroundColor", "#a18c3e")
    $("#all").css("backgroundColor", "transparent")
    $("#card").css("backgroundColor", "transparent")
    $("#web").css("backgroundColor", "transparent")
    $(".all").css("display", "none")
    $(".a2").css("display", "block")
    $(".a3").css("display", "none")
    $(".a4").css("display", "none")
})

$("#card").click(function () {
    $("#card").css("backgroundColor", "#a18c3e")
    $("#web").css("backgroundColor", "transparent")
    $("#all").css("backgroundColor", "transparent")
    $("#app").css("backgroundColor", "transparent")
    $(".a3").css("display", "block")
    $(".a2").css("display", "none")
    $(".all").css("display", "none")
    $(".a4").css("display", "none")
})
$("#web").click(function () {
    $("#web").css("backgroundColor", "#a18c3e")
    $("#card").css("backgroundColor", "transparent")
    $("#all").css("backgroundColor", "transparent")
    $("#app").css("backgroundColor", "transparent")
    $(".a4").css("display", "block")
    $(".a2").css("display", "none")
    $(".a3").css("display", "none")
    $(".all").css("display", "none")
})
$("#all").click(function () {
    $("#all").css("backgroundColor", "#a18c3e")
    $("#app").css("backgroundColor", "transparent")
    $("#web").css("backgroundColor", "transparent")
    $("#card").css("backgroundColor", "transparent")
    $(".a2").css("display", "none")
    $(".a3").css("display", "none")
    $(".a4").css("display", "none")
    $(".all").css("display", "block")
})


$("#und").click(function () {

    $("#und").css("backgroundColor", "#a18c3e")
    $("#mod").css("backgroundColor", "black")
    $("#ius").css("backgroundColor", "black")
    $("#nos").css("backgroundColor", "black")
    $(".acti").css("backgroundColor", "black")
    $(".im2").css("display", "block")
    $(".im1").css("display", "none")
    $(".im4").css("display", "none")
    $(".im3").css("display", "none")
    $(".page2").css("display", "block")
    $(".page1").css("display", "none")
    $(".page4").css("display", "none")
    $(".page3").css("display", "none")
})
$("#nos").click(function () {
    $("#nos").css("backgroundColor", "#a18c3e")
    $("#mod").css("backgroundColor", "black")
    $("#und").css("backgroundColor", "black")
    $("#ius").css("backgroundColor", "black")
    $(".im3").css("display", "block")
    $(".im2").css("display", "none")
    $(".im4").css("display", "none")
    $(".page3").css("display", "block")
    $(".im1").css("display", "none")
    $(".page1").css("display", "none")
    $(".page4").css("display", "none")
    $(".page2").css("display", "none")
})
$("#ius").click(function () {
    $("#ius").css("backgroundColor", "#a18c3e")
    $("#mod").css("backgroundColor", "black")
    $("#und").css("backgroundColor", "black")
    $("#nos").css("backgroundColor", "black")
    $(".im4").css("display", "block")
    $(".im2").css("display", "none")
    $(".page4").css("display", "block")
    $(".im1").css("display", "none")
    $(".page1").css("display", "none")
    $(".page2").css("display", "none")
    $(".page3").css("display", "none")
    $(".im3").css("display", "none")

})
$("#mod").click(function () {
    $("#mod").css("backgroundColor", "#a18c3e")
    $("#nos").css("backgroundColor", "black")
    $("#und").css("backgroundColor", "black")
    $("#ius").css("backgroundColor", "black")
    $(".im1").css("display", "block")
    $(".im2").css("display", "none")
    $(".page1").css("display", "block")
    $(".im4").css("display", "none")
    $(".page4").css("display", "none")
    $(".page2").css("display", "none")
    $(".page3").css("display", "none")
    $(".im3").css("display", "none")

})